collections:
  afdelinger:
    output: true
    permalink: /:slug/
  events:
    output: true
    permalink: /kalender/:path/
  gamle_billeder:
    output: false
  tidligere_spejder_billeder:
    output: false

defaults:
 - 
  scope:
    type: afdelinger
  values:
    layout: afdeling
 -
  scope:
    type: events
  values:
    layout: event
