backend:
  name: github
  repo: soeborggruppe/web
  branch: master

collections:
  - name: afdelinger
    label: Afdelinger
    label_singular: Afdeling
    folder: _afdelinger
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Stort billede", name: "hero_image", widget: "file", required: false}
      - {label: "Aldersgruppe", name: "age_group", widget: "string", required: false}
      - {label: "Mødetid", name: "meeting_time", widget: "string", required: false}
      - {label: "Kontakt-email", name: "contact_email", widget: "string", required: false}
      - label: "Ledere"
        name: "leaders"
        widget: "list"
        field:
          label: Navn
          widget: string
        required: false
      - label: "Filer"
        name: "files"
        widget: "list"
        fields:
          - label: "Navn"
            name: "name"
            widget: "string"
          - label: "Link"
            name: "link"
            widget: "file"
        required: false
      - {label: "Beskrivelse", name: "body", widget: "markdown"}

  - name: events
    label: Events
    label_singular: Event
    folder: _events
    create: true
    slug: "{{date_year}}-{{slug}}"
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - label: "Tags"
        name: "tags"
        widget: "multiselect"
        options: ["Familie", "Mikro", "Mini", "Junior", "Trop", "Skumbaklan", "Vatiklanet", "Peliklan", "Kleptoklan", "Ledergruppen", "Bestyrelsen"]
        required: false
      - {label: "År", name: "date_year", widget: "string"}
      - {label: "Start", name: "date_start", widget: "datetime", format: "YYYY-MM-DDTHH:mm:00"}
      - {label: "Slut", name: "date_end", widget: "datetime", format: "YYYY-MM-DDTHH:mm:00"}
      - {label: "Gruppeweb node ID", name: "old_id", widget: "string", required: false}
      - {label: "Tilmeldingslink", name: "signup_link", widget: "string", required: false}
      - {label: "Beskrivelse", name: "body", widget: "markdown", required: false}

  - name: calendar_years
    label: Kalenderår
    folder: _calendar_years
    create: true
    identifier_field: slug
    fields:
      - {label: "År", name: "slug", widget: "string"}

  - name: pages
    label: Side
    folder: _pages
    create: true
    fields:
      - label: "Layout"
        name: "layout"
        widget: "select"
        default: "page"
        options:
          - label: "Page"
            value: "page"
          - label: "Big header/no styling"
            value: "bigheader"
      - {label: "URL", name: "permalink", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Indhold", name: "body", widget: "markdown"}

media_folder: files
