backend:
  name: github
  repo: soeborggruppe/web
  branch: cms

collections:
  - name: afdelinger
    label: Afdelinger
    label_singular: Afdeling
    folder: _afdelinger
    create: true
    slug: "{{ slug }}"
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "URL", name: "slug", widget: "string", required: false}
      - {label: "Stort billede", name: "hero_image", widget: "file"}
      - {label: "Aldersgruppe", name: "age_group", widget: "string"}
      - {label: "Mødetid", name: "meeting_time", widget: "string"}
      - {label: "Kontakt-email", name: "contact_email", widget: "string"}
      - label: "Ledere"
        name: "leaders"
        widget: "list"
        field:
          label: Navn
          widget: string
      - label: "Filer"
        name: "files"
        widget: "list"
        fields:
          - label: "Navn"
            name: "name"
            widget: "string"
          - label: "Link"
            name: "link"
            widget: "file"
      - {label: "Adresseliste-kode", name: "address_list_code", widget: "string"}
      - {label: "Beskrivelse", name: "body", widget: "markdown"}

  - name: events
    label: Events
    label_singular: Event
    folder: _events
    create: true
    slug: "{{ year }}-{{ slug }}"
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - label: "Tags"
        name: "tags"
        widget: "multiselect"
        options: ["Familie", "Mikro", "Mini", "Junior", "Trop", "Skumbaklan", "Vatiklanet", "Peliklan", "Kleptoklan", "Ledergruppen", "Bestyrelsen"]
      - {label: "Start", name: "date_start", widget: "datetime", format: "YYYY-MM-DDTHH:mm:00"}
      - {label: "Slut", name: "date_end", widget: "datetime", format: "YYYY-MM-DDTHH:mm:00"}
      - {label: "Gruppeweb node ID", name: "old_id", widget: "string", required: false}
      - {label: "Tilmeldingslink", name: "signup_link", widget: "string", required: false}
      - {label: "Beskrivelse", name: "body", widget: "markdown"}

  - name: calendar_years
    label: Kalenderår
    folder: _calendar_years
    create: true
    fields:
      - {label: "År", name: "slug", widget: "string"}

media_folder: files
