backend:
  name: github
  repo: soeborggruppe/web
  branch: cms

collections:
  - name: events
    label: Events
    label_singular: Event
    folder: _events
    create: true
    slug: "{{ year }}-{{ slug }}"
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - label: "Tags"
        name: "tags"
        widget: "multiselect"
        options: ["Familie", "Mikro", "Mini", "Junior", "Trop", "Skumbaklan", "Vatiklanet", "Peliklan", "Kleptoklan", "Ledergruppen", "Bestyrelsen"]
      - {label: "Start", name: "date_start", widget: "datetime", format: "YYYY-MM-DDTHH:mm:00"}
      - {label: "Slut", name: "date_end", widget: "datetime", format: "YYYY-MM-DDTHH:mm:00"}
      - {label: "Gruppeweb node ID", name: "old_id", widget: "string", required: false}
      - {label: "Tilmeldingslink", name: "signup_link", widget: "string", required: false}
      - {label: "Beskrivelse", name: "body", widget: "markdown"}

media_folder: files
